spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_CONTAINER_NAME:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:dss}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  application:
    name: WebServer
  profiles:
    active: prod

server:
  port: 8081

generator:
  service:
    url: ${GENERATOR_SERVICE_URL:http://localhost:8082}
export:
  service:
    url: ${EXPORT_SERVICE_URL:http://localhost:8083}


logging:
  level:
    org:
      hibernate:
        SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
